---
apiVersion: v1
kind: Service
metadata:
  name: apisix-loadbalancer
  namespace: ingress-apisix
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080